# Generated by Django 3.2.3 on 2021-06-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytype',
            name='type_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quote'),
        ),
    ]
