# Generated by Django 3.2.3 on 2021-06-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20210601_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.CharField(default='sd', max_length=20, verbose_name='Quote'),
            preserve_default=False,
        ),
    ]
