# Generated by Django 3.2.3 on 2021-06-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_auto_20210602_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='policy',
        ),
        migrations.AddField(
            model_name='quote',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policy.policytype'),
        ),
    ]
