# Generated by Django 3.2.3 on 2021-06-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_alter_quote_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='name',
            field=models.CharField(default='aa', max_length=200, unique=True, verbose_name='Insurance Name'),
            preserve_default=False,
        ),
    ]
